Ugly attempt to support OIDC with UUIDs, 2.25.xxx
PeculiarVentures/ASN1.js pull request #65
Opened 2021-12-06 17:56 UTC by lokkilok

Almost certainly not the best way to to this, and for sure not very efficient, but it seems to work. Perhaps can serve as an inspiration for a proper fix.

2021-12-07 20:38 UTC, rmhrisk commented
1?

2021-12-08 13:13 UTC, lokkilok commented
As far as I can see both option 1 and 2 could be ok for pretty much anybody who would need this support for OIDs with UUIDs. With option 2 any code that needs this support would have to require that the browser/environment supports BigInts. I guess that this is not too much asked....

2021-12-09 14:03 UTC, microshine commented
https://github.com/zloirock/core-js#missing-polyfills
> ES BigInt can't be polyfilled since it requires changes in the behavior of operators, you could find more info here. You could try to use JSBI.

Looks like it's impossible to do the 1st case

2021-12-09 14:14 UTC, microshine requested changes

2021-12-09 14:14 UTC, microshine commented on src/asn1.js
> + set valueBigInt(value) {
Let's add an assert function like
```js
function assertBigInt() {
  if (typeof BigInt === "undefined") {
    throw new Error("BigInt is not defined. Your environment doesn't implement BigInt.")
  }
}
```

and use it here

```suggestion
	set valueBigInt(value)
	{
		assertBigInt();
```

2021-12-09 14:14 UTC, microshine commented on src/asn1.js
> + set valueBigInt(value) {
And please format your changes. Use TAB instead of SPACE for padding

2021-12-09 14:14 UTC, microshine commented on src/asn1.js
> +        let sidValue = BigInt(sid)
```suggestion
        assertBigInt();
        const sidValue = BigInt(sid);
```

2021-12-09 15:57 UTC, rmhrisk commented
> https://github.com/zloirock/core-js#missing-polyfills
> 
> > ES BigInt can't be polyfilled since it requires changes in the behavior of operators, you could find more info here. You could try to use JSBI.
> 
> Looks like it's impossible to do the 1st case
Sounds like 2 is the winner?

2021-12-10 06:35 UTC, lokkilok commented
Added the suggestions, thanks! However, I now noted that the code already has a reference to BigInt in the code, in the toString() method of the INTEGER block. In other words the ASN1.js library was already relying on BigInt support....

2021-12-20 07:09 UTC, lokkilok commented
@microshine: now that I more or less incorporated the changes you requested (albeit not verbatim) when do you think this will be merged?

2021-12-23 11:04 UTC, microshine approved these changes

2021-12-23 11:05 UTC, merged

2021-12-23 11:11 UTC, microshine commented
@lokkilok Thank you for the work you did.

I've published the new version `asn1js@2.2.0`. Please try it

2021-12-23 11:36 UTC, lokkilok commented
Lightly tested and seemed ok! Thanks!