Adds support for ASN1 Real BER encoding decoding
PeculiarVentures/ASN1.js pull request #79
Opened 2022-10-31 15:13 UTC by JanFellner

2022-11-24 08:49 UTC, microshine requested changes
@JanFellner thank you for your update. I'd like to include these features into the asn1js module.

I've requested some changes

This build works fine with pkijs and @peculiar/asn1-schema

2022-11-24 08:49 UTC, microshine commented on test/asn1choice.spec.ts
> +function buf2hex(buffer: ArrayBuffer): string {
I see you implemented some helping functions like `buf2hex`, `hex2buf` and use their copies in each test file. `pvtsutils` has `Convert` static class which implements this functionality, please use it

2022-11-24 08:49 UTC, microshine commented on src/schema.ts
> +  // The path within the structure we are parsing (object:subobject:element)
use doc comment

2022-11-24 08:49 UTC, microshine commented on tsconfig.json
> +    "sourceMap": true,
What do you use `sourceMap` for? We don't add source map files into the build folder and it's not needed for debuging

2022-11-24 08:49 UTC, microshine commented on .gitignore
> +src/*.js
looks like you build JS files using `tsc` command. Please see this extension https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-mocha-test-adapter. It allows runnig  mocha tests without `sourceMap`, compiling and `launch.json` file

2022-11-24 09:51 UTC, JanFellner commented
Hi Stephan, 

Thanks for catching up.

I made so many changes in the repo and accidently setup the PR from the master branch.  So the core idea of adding asn real is blurred with so many other changes that it does not make sense to merge it right now.

To give you a little context. I am implementing asn.1 BER as communication layer using ROSE. Doing this I see several things that need to get adopted/improved in the lib. I've been working with the lib for the last 4 weeks and made several improvements. The changes you require are easy to adopt the question is if it makes sense to merge them all.

Things I have touches.
- adding real
- adding contextual optional params where the encoded data says a value is context specific and points to the schema which value (and therefor type) it is.
- fixes for repeated values as these have not been validated.
- after parsing the data against the schema the attribute names are taken over to the parsed data to have them accessible by name.
- the schema validation returns an array of errors giving the context where a parsing error has been seen. 
- and other tweaks to improve usability.

- all extensions i made are test covered. 
- all existing test are passing
- the addtional tests also explain the usage of the library. (how to handle optionals. repeated. Etc.) 

In case you think about taking those changes over I would place them as a new major version cause they are rather large in the end.

Would be great if you could check that on your side in a productive environment if it still does what it is expected to do.

The changes I made are matching to BER encoded objects by the snacc and objective systems compilers which we use today for our products.

If you think this does not really make sense for you, we would start to maintain an own fork. However you decide let me know 😉

Comments welcome.. 

Jan

2022-12-02 10:59 UTC, JanFellner commented
I adopted all your recommondations but we decided to maintain our own version of the repo as the amount of changes especially in the schema validation concering implicit notated objects is rather large.
I do not want to put you into the need of maintaining stuff you don´t need.

2022-12-02 10:59 UTC, closed without merging